### ISSUE TITLE
Errors intalling

### ISSUE THREAD

**Issue by Farrit1184** [kalimah-apps/colors-plus-plus#1]
When installing through Brackets or downloading the zip file, I receive an extension error. If I reboot, it continues to receive the extension error.

**Comment by kalimah-apps** [comment]
What is the error message?
Is it similar to this: **Installation Failed. The extension encountered an error while starting up**. If so try downloading or updating the extrusion through the extension manager. The issue should have been resolved.

**Comment by fernamp** [comment]
Keeps telling about the starting error. Testes every installation available. Changed the name for the folder, etc. Nothing works.

**Comment by Farrit1184** [comment]
The error simply says "Extension error" 
![image](https://user-images.githubusercontent.com/31215800/29581320-e36c19a8-8746-11e7-9c91-c2206cc203f7.png)

**Comment by kminx** [comment]
I'm getting the same thing. Here's the error:
<img width="775" alt="screenshot 2017-08-22 11 55 04" src="https://user-images.githubusercontent.com/1304872/29582320-1cdcb19a-8731-11e7-9ede-48cc4e4b096a.png">

**Comment by anandisrocking007** [comment]
Getting the same error here and even cant download package from the brackets extensions site gives this error
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>83D9C0D17C87EC2F</RequestId>
<HostId>
a96T+5XPfh3ThDWIih5DMYAS2Ije+wB9YUUtPmcaS3ATCfZ4NNu8/RK+M1pANW/YopLCO8rihBk=
</HostId>
</Error>`

**Comment by Gareth10jones** [comment]
Same error here, be great to get this working

**Comment by kalimah-apps** [comment]
Ok. I tried installing the extension again on my computer and it worked fine,

Maybe we can try two things:
1- add the extension directly to **user** folder. If you are new to Brackets then you can find the folder under **Help menu > show Extensions Folder**. Then download the extension from the GitHub repo (not from the brackets extensions registry).

2- The other option is to open developer tools (F12). Click on the console tab and clean it. Then go through the installation process through the extensions manager. Once the error message show click close and then go back to the console and check if there are any error messages appeared. If so copy them and past them here so I can see what causing the error.

**Comment by Gareth10jones** [comment]
Hi

Thanks for the update.  I have tried both of your suggestions (as the first failed.  The colsole error is:

`/utils/ExtensionLoader.js:227 [Extension] failed to load /Users/garethjones/Library/Application Support/Brackets/extensions/user/kalimah-colors-plus-plus - SyntaxError: Unexpected end of inputerrback @ /utils/ExtensionLoader.js:227(anonymous function) @ thirdparty.min.js:19j @ thirdparty.min.js:19k.fireWith @ thirdparty.min.js:19e.(anonymous function) @ thirdparty.min.js:19j @ thirdparty.min.js:19k.fireWith @ thirdparty.min.js:19e.(anonymous function) @ thirdparty.min.js:19(anonymous function) @ require.js:132(anonymous function) @ require.js:1164each @ require.js:57Module.emit @ require.js:1163(anonymous function) @ require.js:757(anonymous function) @ require.js:132(anonymous function) @ require.js:132(anonymous function) @ require.js:1164each @ require.js:57Module.emit @ require.js:1163(anonymous function) @ require.js:539each @ require.js:57onError @ require.js:532Module.check @ require.js:894(anonymous function) @ require.js:1121(anonymous function) @ require.js:132(anonymous function) @ require.js:1164each @ require.js:57Module.emit @ require.js:1163Module.check @ require.js:925Module.enable @ require.js:1151Module.init @ require.js:782(anonymous function) @ require.js:967(anonymous function) @ require.js:132(anonymous function) @ require.js:1164each @ require.js:57Module.emit @ require.js:1163Module.check @ require.js:925Module.enable @ require.js:1151Module.init @ require.js:782(anonymous function) @ require.js:999(anonymous function) @ require.js:132text.finishLoad @ text.js:152(anonymous function) @ text.js:188xhr.onreadystatechange @ text.js:295
/utils/ExtensionLoader.js:231 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (file:///Users/garethjones/Library/Application%20Support/Brackets/extensions/user/kalimah-colors-plus-plus/optionsPanel.js:49:34)
    at Object.context.execCb (file:///Applications/Brackets.app/Contents/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///Applications/Brackets.app/Contents/www/thirdparty/requirejs/require.js:869:55)
    at Object.<anonymous> (file:///Applications/Brackets.app/Contents/www/thirdparty/requirejs/require.js:1121:34)
    at file:///Applications/Brackets.app/Contents/www/thirdparty/requirejs/require.js:132:23
    at file:///Applications/Brackets.app/Contents/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///Applications/Brackets.app/Contents/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.emit (file:///Applications/Brackets.app/Contents/www/thirdparty/requirejs/require.js:1163:17)
    at Object.Module.check (file:///Applications/Brackets.app/Contents/www/thirdparty/requirejs/require.js:925:30)`

**Comment by abdul-alhasany** [comment]
Ok. Thanks for the code. I edited the extension and uploaded a new version. Please delete the old one, restart brackets and then install the new one. If an error occurs follow the same process an copy console log here (it might be a good idea for next time to copy the line just right before the code you pasted).

**Comment by Gareth10jones** [comment]
Tried again via the install method and all working perfectly.

Thanks for your help and keep up the great work with the extension!

**Comment by abdul-alhasany** [comment]
Glad to hear.
